// src/components/NavBar.vue
<script setup>
import NavItem from "./NavItem.vue";
</script>

<template>
  <nav class="absolute w-full flex justify-center items-center">
    <div
      class="absolute left-[5%] sm:left-[10%] rounded-full w-20 h-20 mt-10 bg-black z-50"
    ></div>
    <ul
      class="relative z-50 mt-10 flex rounded-full bg-white/90 px-3 text-sm font-medium text-zinc-800 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur dark:bg-zinc-800/90 dark:text-zinc-200 dark:ring-white/10"
    >
      <NavItem linkName="About" />
      <NavItem linkName="Work" />
      <NavItem linkName="Projects" />
      <NavItem linkName="Contact" />
    </ul>
    <div></div>
  </nav>
</template>

// version2.0/src/components/nav/NavBar.tsx
import { LinkButton } from "../global/LinkButton";
import { WebsiteLogo } from "../global/WebsiteLogo";
import { NavLink } from "./NavLink";

interface Props {
  refsArray: React.RefObject<HTMLDivElement>[];
}

export const NavBar = ({ refsArray }: Props) => {
  return (
    <nav className="absolute w-full top-5 flex justify-center">
      <div className="w-fit flex items-center gap-6 rounded-lg border-[1px] border-projectBorder bg-projectForeground p-2 text-sm text-projectDark">
        <WebsiteLogo
          className="ml-2 h-7 w-7 cursor-pointer"
          targetSection={refsArray[0]}
        />
        <NavLink text="About" targetSection={refsArray[1]} />
        <NavLink text="Projects" targetSection={refsArray[2]} />
        <NavLink text="Experience" targetSection={refsArray[3]} />
        <NavLink text="Contact" targetSection={refsArray[4]} />

        <LinkButton text="My Resume" />
      </div>
    </nav>
  );
};
